"use client";

import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import {
  ArrowRight,
  Brain,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Cookie,
  Download,
  Droplet,
  Dumbbell,
  FileText,
  Film,
  Flame,
  Lock,
  Minus,
  Moon,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  ShieldCheck,
  Sparkles,
  Sun,
  Sunrise,
  TestTube,
  Timer,
  Trash2,
  Upload,
  Utensils,
  X,
} from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";

import { HealthTools } from "@/components/dashboard/HealthTools";
import { MealPlanBuilder } from "@/components/dashboard/MealPlanBuilder";
import {
  DAY_CALORIE_TARGET,
  WEEK_PLAN,
  type Achievements,
  type BlockType,
  type DayBlock,
  type PlanState,
  type RoutineItem,
  activatePlan,
  addDayBlock,
  applyPlanBlocks,
  addRoutineItem,
  fetchAchievements,
  fetchDayBlocks,
  fetchDoneIds,
  fetchPlanState,
  fetchRoutineExtras,
  removeDayBlock,
  removeRoutineItem,
  resetPlan,
  toggleDone,
  updateDayBlock,
} from "@/lib/gethealthy/service";
import { matchFood, parseCount, parseGrams } from "@/lib/gethealthy/foods";
import { DIETS, DIET_META, fetchMeals, youtubeId, type Diet, type Meal } from "@/lib/meals/service";
import { planDayToBlocks } from "@/lib/gethealthy/from-meal-plan";
import type { PlanSection, PlannedDay } from "@/lib/meals/plan-text";

const EASE = [0.22, 1, 0.36, 1] as const;
const CARD = "rounded-3xl bg-white shadow-[0_2px_4px_-2px_rgba(15,58,38,0.08),0_16px_36px_-20px_rgba(15,58,38,0.30)] ring-1 ring-[#0f3a26]/10";

const BLOCK_META: Record<BlockType, { icon: React.ComponentType<{ className?: string }>; tint: string }> = {
  hydration: { icon: Droplet, tint: "bg-[#0ea5b5]/12 text-[#0e7d88]" },
  workout: { icon: Dumbbell, tint: "bg-[#006E42]/12 text-[#006E42]" },
  meal: { icon: Utensils, tint: "bg-[#c79a3d]/16 text-[#9c7426]" },
  snack: { icon: Cookie, tint: "bg-[#c79a3d]/16 text-[#9c7426]" },
  mindfulness: { icon: Brain, tint: "bg-[#7c6bd6]/14 text-[#5f52ad]" },
  habit: { icon: CheckCircle2, tint: "bg-[#006E42]/12 text-[#006E42]" },
};

const TYPE_LABEL: Record<BlockType, string> = {
  hydration: "Hydration", workout: "Workout", meal: "Meal", snack: "Snack", mindfulness: "Mindfulness", habit: "Habit",
};

const DAY_PARTS: { key: string; label: string; icon: React.ComponentType<{ className?: string }> }[] = [
  { key: "morning", label: "Morning", icon: Sunrise },
  { key: "afternoon", label: "Afternoon", icon: Sun },
  { key: "evening", label: "Evening", icon: Moon },
  { key: "anytime", label: "Anytime", icon: Clock },
];
function partOfDay(time?: string): string {
  if (!time) return "anytime";
  const h = parseInt(time.slice(0, 2), 10);
  if (Number.isNaN(h)) return "anytime";
  if (h < 12) return "morning";
  if (h < 17) return "afternoon";
  return "evening";
}

const wait = (ms: number) => new Promise((r) => setTimeout(r, ms));
const PROCESS_STEPS = ["Reading your report", "Extracting key markers", "Building your day and week plan"];

/* ------------------------------ print (Save as PDF) ------------------------------ */

function printDoc(title: string, inner: string) {
  if (typeof document === "undefined") return;
  const iframe = document.createElement("iframe");
  iframe.setAttribute("aria-hidden", "true");
  iframe.style.cssText = "position:fixed;right:0;bottom:0;width:0;height:0;border:0;";
  document.body.appendChild(iframe);
  const doc = iframe.contentWindow?.document;
  if (!doc) { iframe.remove(); return; }
  doc.open();
  doc.write(`<!doctype html><html><head><meta charset="utf-8"><title>${title}</title><style>
    *{box-sizing:border-box;font-family:-apple-system,Segoe UI,Roboto,sans-serif;}
    body{margin:0;padding:34px;color:#0f3a26;}
    h1{font-size:22px;margin:0 0 2px;}
    .sub{color:#5b7266;font-size:12px;margin:0 0 20px;}
    .row{display:flex;justify-content:space-between;gap:12px;padding:9px 0;border-bottom:1px solid #e3ede7;}
    .t{font-weight:600;font-size:13px;}
    .d{color:#5b7266;font-size:12px;}
    .day{margin:14px 0;padding:12px 14px;border:1px solid #e3ede7;border-radius:12px;}
    .day h3{margin:0 0 4px;font-size:14px;}
    .chip{display:inline-block;margin:4px 5px 0 0;padding:3px 9px;background:#eef5f0;border-radius:999px;font-size:11px;}
    .foot{margin-top:26px;font-size:11px;color:#9fb0a7;}
  </style></head><body>${inner}<p class="foot">Generated by SuppAI · Get Healthy</p></body></html>`);
  doc.close();
  iframe.contentWindow?.focus();
  setTimeout(() => { iframe.contentWindow?.print(); setTimeout(() => iframe.remove(), 800); }, 300);
}
function buildDayHtml(blocks: DayBlock[], doneIds: string[]) {
  const rows = blocks
    .map((b) => `<div class="row"><div><div class="t">${b.time || "Anytime"} · ${b.title}${doneIds.includes(b.id) ? " ✓" : ""}</div><div class="d">${b.detail || ""}</div></div><div class="d">${b.kcal ? b.kcal + " kcal" : ""}</div></div>`)
    .join("");
  return `<h1>Daily plan</h1><p class="sub">Your routine for today</p>${rows}`;
}
function buildWeekHtml(routine: RoutineItem[]) {
  const days = WEEK_PLAN.map((d) => {
    const items = d.items.map((i) => `<span class="chip">${i}</span>`).join("");
    const extras = routine.filter((r) => r.day === d.key).map((r) => `<span class="chip">+ ${r.label}</span>`).join("");
    return `<div class="day"><h3>${d.label} — ${d.focus}</h3><div class="d">${d.kcal} kcal target</div><div>${items}${extras}</div></div>`;
  }).join("");
  return `<h1>Weekly plan</h1><p class="sub">Your 7-day plan</p>${days}`;
}

/* ============================================================= ROOT ======= */

type AddInit = { mode: "today" | "routine"; day: string; time?: string };

function nowHHMM() {
  const now = new Date();
  return `${String(now.getHours()).padStart(2, "0")}:${String(now.getMinutes()).padStart(2, "0")}`;
}

export function GetHealthyHome() {
  const [state, setState] = useState<PlanState | null>(null);
  const [doneIds, setDoneIds] = useState<string[]>([]);
  const [blocks, setBlocks] = useState<DayBlock[]>([]);
  const [routine, setRoutine] = useState<RoutineItem[]>([]);
  const [ach, setAch] = useState<Achievements | null>(null);
  const [proc, setProc] = useState<{ active: boolean; step: number }>({ active: false, step: 0 });
  const [recipe, setRecipe] = useState<Meal | null>(null);
  const [add, setAdd] = useState<AddInit | null>(null);
  const [editMeal, setEditMeal] = useState<DayBlock | null>(null);
  const fileRef = useRef<HTMLInputElement>(null);
  const reduce = useReducedMotion();

  useEffect(() => {
    fetchPlanState().then(setState);
    fetchDoneIds().then(setDoneIds);
    fetchDayBlocks().then(setBlocks);
    fetchRoutineExtras().then(setRoutine);
    fetchAchievements().then(setAch);
  }, []);

  async function runProcessing(name: string) {
    const gap = reduce ? 250 : 800;
    setProc({ active: true, step: 0 });
    await wait(gap); setProc({ active: true, step: 1 });
    await wait(gap); setProc({ active: true, step: 2 });
    await wait(gap + 200);
    setState(await activatePlan(name));
    setBlocks(await fetchDayBlocks());
    setProc({ active: false, step: 0 });
  }

  /* A generated plan lands on the schedule in short form (dish, time, key
     numbers), grouped under Morning, Afternoon and Evening like everything else. */
  async function useMealPlanDay(day: PlannedDay, sections: PlanSection[]) {
    if (state?.status !== "active") setState(await activatePlan("your meal plan"));
    setBlocks(await applyPlanBlocks(planDayToBlocks(day, sections)));
    window.setTimeout(() => document.getElementById("today-schedule")?.scrollIntoView({ behavior: reduce ? "auto" : "smooth", block: "start" }), 120);
  }

  const browse = () => fileRef.current?.click();
  const active = state?.status === "active" && !proc.active;

  return (
    <div className="px-4 py-5 md:px-10 md:py-6">
      <input ref={fileRef} type="file" accept=".pdf,application/pdf" className="hidden" onChange={(e) => { const f = e.target.files?.[0]; if (f) runProcessing(f.name); }} />

      {proc.active ? (
        <Fade><ProcessingCard step={proc.step} /></Fade>
      ) : active ? (
        <ActivePlan
          onUseMealPlanDay={useMealPlanDay}
          state={state!}
          doneIds={doneIds}
          blocks={blocks}
          routine={routine}
          ach={ach}
          onToggle={async (id) => setDoneIds(await toggleDone(id))}
          onRemoveBlock={async (id) => setBlocks(await removeDayBlock(id))}
          onRemoveRoutine={async (id) => setRoutine(await removeRoutineItem(id))}
          onEditMeal={(b) => setEditMeal(b)}
          onOpenRecipe={setRecipe}
          onAdd={(init) => setAdd({ ...init, time: nowHHMM() })}
          onBrowse={browse}
          onReset={async () => { setState(await resetPlan()); setDoneIds([]); setBlocks(await fetchDayBlocks()); setRoutine([]); }}
          onDownloadDay={() => printDoc("SuppAI Daily plan", buildDayHtml(blocks, doneIds))}
          onDownloadWeek={() => printDoc("SuppAI Weekly plan", buildWeekHtml(routine))}
        />
      ) : (
        <EmptyPlan onUseMealPlanDay={useMealPlanDay} onBrowse={browse} onFile={(f) => { if (f) runProcessing(f.name); }} onSample={() => runProcessing("blood-report-jane.pdf")} onOpenRecipe={setRecipe} />
      )}

      <RecipeModal recipe={recipe} onClose={() => setRecipe(null)} onLog={async (r) => { setBlocks(await addDayBlock({ time: "", type: "meal", title: r.name, detail: "From recipes", kcal: r.kcal })); setRecipe(null); }} canLog={active} />

      <AddEventModal
        init={add}
        onClose={() => setAdd(null)}
        onAddDay={async (b) => { setBlocks(await addDayBlock(b)); setAdd(null); }}
        onAddRoutine={async ({ days, label, kind }) => {
          let list = routine;
          for (const day of days) list = await addRoutineItem({ day, label, kind });
          setRoutine(list);
          setAdd(null);
        }}
      />

      <MealEditor block={editMeal} onClose={() => setEditMeal(null)} onSave={async (id, patch) => { setBlocks(await updateDayBlock(id, patch)); setEditMeal(null); }} />
    </div>
  );
}

/* ------------------------------ motion + heading ------------------------------ */

function Fade({ children }: { children: React.ReactNode }) {
  const reduce = useReducedMotion();
  return <motion.div initial={reduce ? false : { opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.45, ease: EASE }}>{children}</motion.div>;
}
function Stagger({ i, children }: { i: number; children: React.ReactNode }) {
  const reduce = useReducedMotion();
  return <motion.section initial={reduce ? false : { opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, ease: EASE, delay: reduce ? 0 : i * 0.08 }}>{children}</motion.section>;
}
function Heading({ label, title, locked, action }: { label: string; title: string; locked?: boolean; action?: React.ReactNode }) {
  return (
    <div className="mb-3 flex items-center gap-2.5">
      <span className="text-[11px] font-semibold uppercase tracking-[0.18em] text-[#006E42]/70">{label}</span>
      <span className="h-px flex-1 bg-[#0f3a26]/10" />
      <h2 className="text-[15px] font-bold tracking-tight text-[#0f3a26]">{title}</h2>
      {locked && <Lock className="h-3.5 w-3.5 text-[#0f3a26]/35" />}
      {action}
    </div>
  );
}

/* ============================================================= EMPTY ====== */

function EmptyPlan({ onUseMealPlanDay, onBrowse, onFile, onSample, onOpenRecipe }: { onUseMealPlanDay: (day: PlannedDay, sections: PlanSection[]) => Promise<void>; onBrowse: () => void; onFile: (f?: File | null) => void; onSample: () => void; onOpenRecipe: (r: Meal) => void }) {
  return (
    <div className="space-y-6 md:space-y-8">
      <Stagger i={0}><HealthTools /></Stagger>
      <Stagger i={1}><UploadSpotlight onBrowse={onBrowse} onFile={onFile} onSample={onSample} /></Stagger>

      <Stagger i={2}><MealPlanBuilder onUseDay={onUseMealPlanDay} /></Stagger>

      <Stagger i={3}>
        <Heading label="Eat well" title="Recipes for you" action={<span className="text-[11px] text-[#0f3a26]/40">scroll for more</span>} />
        <RecipeRail onOpen={onOpenRecipe} />
      </Stagger>
    </div>
  );
}

function UploadSpotlight({ onBrowse, onFile, onSample }: { onBrowse: () => void; onFile: (f?: File | null) => void; onSample: () => void }) {
  const [drag, setDrag] = useState(false);
  const steps = [{ icon: Upload, label: "Upload report" }, { icon: Sparkles, label: "We analyse it" }, { icon: CheckCircle2, label: "Get your plans" }];
  return (
    <div className={`${CARD} overflow-hidden`}>
      <div className="mx-auto max-w-2xl px-6 py-10 text-center md:py-12">
        <span className="inline-flex items-center gap-1.5 rounded-full bg-[#006E42]/8 px-3 py-1 text-[11px] font-semibold uppercase tracking-wider text-[#006E42]"><Sparkles className="h-3 w-3" />Start here</span>
        <h1 className="mx-auto mt-4 max-w-xl text-[27px] font-bold leading-tight tracking-tight text-[#0f3a26] md:text-[30px]">Upload your report, get a plan you can follow.</h1>
        <p className="mx-auto mt-2.5 max-w-md text-[13.5px] leading-relaxed text-[#0f3a26]/60">Drop your latest lab test PDF. We read your markers and build a day-by-day routine plus a full weekly plan around your body.</p>
        <div
          onDragOver={(e) => { e.preventDefault(); setDrag(true); }}
          onDragLeave={() => setDrag(false)}
          onDrop={(e) => { e.preventDefault(); setDrag(false); onFile(e.dataTransfer.files?.[0]); }}
          className={`mt-7 flex flex-col items-center rounded-3xl border-2 border-dashed px-6 py-9 transition-colors ${drag ? "border-[#006E42] bg-[#006E42]/[0.05]" : "border-[#0f3a26]/15 bg-[#f1f7f3]"}`}
        >
          <motion.span animate={drag ? { y: -5, scale: 1.03 } : { y: 0, scale: 1 }} transition={{ duration: 0.3, ease: EASE }} className="grid h-16 w-16 place-items-center rounded-2xl bg-white text-[#006E42] shadow-[0_10px_24px_-12px_rgba(15,58,38,0.5)] ring-1 ring-[#0f3a26]/8"><FileText className="h-7 w-7" /></motion.span>
          <p className="mt-4 text-[14px] font-semibold text-[#0f3a26]">Drop your report PDF here</p>
          <button onClick={onBrowse} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-[#006E42] px-5 py-2.5 text-[13px] font-semibold text-white transition hover:bg-[#005634] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#006E42]/40"><Upload className="h-4 w-4" />Browse files</button>
          <button onClick={onSample} className="mt-3 text-[11.5px] font-medium text-[#006E42] underline-offset-2 transition hover:underline">No report handy? Try a sample</button>
        </div>

        {/* Book a test if none */}
        <div className="mt-5 flex flex-col items-center gap-2 rounded-2xl bg-[#f1f7f3] p-4 ring-1 ring-inset ring-[#0f3a26]/[0.08] sm:flex-row sm:justify-between sm:text-left">
          <div className="flex items-center gap-3">
            <span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-white text-[#006E42] ring-1 ring-inset ring-[#0f3a26]/8"><TestTube className="h-4 w-4" /></span>
            <p className="text-[12.5px] leading-tight text-[#0f3a26]/70">Don&apos;t have a test report yet?<br className="hidden sm:block" /><span className="font-semibold text-[#0f3a26]">Book a lab test</span> and we&apos;ll take it from there.</p>
          </div>
          <Link href="/dashboard/diagnose" className="inline-flex shrink-0 items-center gap-1.5 rounded-xl bg-white px-3.5 py-2 text-[12.5px] font-semibold text-[#006E42] ring-1 ring-inset ring-[#006E42]/25 transition hover:bg-[#006E42] hover:text-white">Book it now<ArrowRight className="h-3.5 w-3.5" /></Link>
        </div>

        <div className="mt-7 flex flex-wrap items-center justify-center gap-2 text-[#0f3a26]/70">
          {steps.map((s, i) => (
            <div key={s.label} className="flex items-center gap-2">
              <span className="inline-flex items-center gap-1.5 rounded-full bg-[#f1f7f3] px-3 py-1.5 text-[11.5px] font-medium ring-1 ring-inset ring-[#0f3a26]/[0.08]"><s.icon className="h-3.5 w-3.5 text-[#006E42]" />{s.label}</span>
              {i < steps.length - 1 && <ArrowRight className="h-3.5 w-3.5 text-[#0f3a26]/30" />}
            </div>
          ))}
        </div>
        <p className="mt-4 inline-flex items-center gap-1.5 text-[11px] text-[#0f3a26]/40"><ShieldCheck className="h-3.5 w-3.5" />Private and encrypted. PDF up to 20 MB.</p>
      </div>
    </div>
  );
}


/* ========================================================== PROCESSING ==== */

function ProcessingCard({ step }: { step: number }) {
  const pct = ((step + 1) / PROCESS_STEPS.length) * 100;
  return (
    <div className={`${CARD} mx-auto max-w-xl p-7 md:p-9`}>
      <div className="flex flex-col items-center text-center">
        <span className="relative grid h-14 w-14 place-items-center rounded-2xl bg-[#006E42]/8 text-[#006E42]">
          <motion.span className="absolute inset-0 rounded-2xl ring-2 ring-[#006E42]/30" animate={{ scale: [1, 1.18, 1], opacity: [0.6, 0, 0.6] }} transition={{ duration: 1.4, repeat: Infinity, ease: "easeOut" }} />
          <Sparkles className="h-6 w-6" />
        </span>
        <h2 className="mt-4 text-[17px] font-bold tracking-tight text-[#0f3a26]">Analysing your report</h2>
        <p className="text-[12.5px] text-[#0f3a26]/55">Building your day and weekly plan.</p>
      </div>
      <div className="mt-6 h-1.5 w-full overflow-hidden rounded-full bg-[#0f3a26]/8"><motion.div className="h-full rounded-full bg-[#006E42]" animate={{ width: `${pct}%` }} transition={{ duration: 0.5, ease: EASE }} /></div>
      <ul className="mx-auto mt-5 max-w-sm space-y-2.5">
        {PROCESS_STEPS.map((label, i) => {
          const done = i < step; const current = i === step;
          return (
            <li key={i} className="flex items-center gap-3">
              <span className={`grid h-6 w-6 place-items-center rounded-full transition-colors ${done ? "bg-[#006E42] text-white" : current ? "bg-[#006E42]/12 text-[#006E42]" : "bg-[#0f3a26]/8 text-[#0f3a26]/40"}`}>
                {done ? <Check className="h-3.5 w-3.5" /> : current ? <motion.span className="h-2 w-2 rounded-full bg-[#006E42]" animate={{ opacity: [1, 0.3, 1] }} transition={{ duration: 1, repeat: Infinity }} /> : <span className="h-1.5 w-1.5 rounded-full bg-current" />}
              </span>
              <span className={`text-[13px] ${done || current ? "font-semibold text-[#0f3a26]" : "text-[#0f3a26]/45"}`}>{label}</span>
            </li>
          );
        })}
      </ul>
    </div>
  );
}

/* ============================================================== ACTIVE ==== */

function ActivePlan(props: {
  onUseMealPlanDay: (day: PlannedDay, sections: PlanSection[]) => Promise<void>;
  state: PlanState; doneIds: string[]; blocks: DayBlock[]; routine: RoutineItem[]; ach: Achievements | null;
  onToggle: (id: string) => void; onRemoveBlock: (id: string) => void; onRemoveRoutine: (id: string) => void;
  onEditMeal: (b: DayBlock) => void;
  onOpenRecipe: (r: Meal) => void; onAdd: (init: AddInit) => void; onBrowse: () => void; onReset: () => void;
  onDownloadDay: () => void; onDownloadWeek: () => void;
}) {
  const { onUseMealPlanDay, state, doneIds, blocks, routine, ach, onToggle, onRemoveBlock, onRemoveRoutine, onEditMeal, onOpenRecipe, onAdd, onBrowse, onReset, onDownloadDay, onDownloadWeek } = props;
  const todayKey = WEEK_PLAN[Math.min(Math.max(state.day - 1, 0), WEEK_PLAN.length - 1)].key;
  const doneCount = blocks.filter((b) => doneIds.includes(b.id)).length;

  return (
    <div className="space-y-6">
      <Stagger i={0}><ActiveHeader state={state} onAdd={() => onAdd({ mode: "today", day: todayKey })} onBrowse={onBrowse} onReset={onReset} /></Stagger>

      <Stagger i={1}><HealthTools /></Stagger>

      <Stagger i={2}>
        <div className="grid grid-cols-12 items-start gap-4 md:gap-6">
          {/* left: editable day timeline */}
          <div className="col-span-12 xl:col-span-8">
            <div id="today-schedule" className={`${CARD} scroll-mt-4 p-5 md:p-6`}>
              <div className="mb-4 flex flex-wrap items-center justify-between gap-2">
                <div className="flex items-baseline gap-2">
                  <h2 className="text-[15px] font-bold tracking-tight text-[#0f3a26]">Today</h2>
                  <span className="text-[11.5px] text-[#0f3a26]/50">{doneCount}/{blocks.length} done</span>
                </div>
                <div className="flex items-center gap-1.5">
                  <button onClick={onDownloadDay} className="inline-flex items-center gap-1.5 rounded-lg bg-[#f1f7f3] px-2.5 py-1.5 text-[11.5px] font-semibold text-[#0f3a26]/70 ring-1 ring-inset ring-[#0f3a26]/[0.08] transition hover:text-[#006E42]"><Download className="h-3.5 w-3.5" />PDF</button>
                  <button onClick={() => onAdd({ mode: "today", day: todayKey })} className="inline-flex items-center gap-1.5 rounded-lg bg-[#006E42] px-2.5 py-1.5 text-[11.5px] font-semibold text-white transition hover:bg-[#005634]"><Plus className="h-3.5 w-3.5" />Add</button>
                </div>
              </div>
              <DayTimeline blocks={blocks} doneIds={doneIds} onToggle={onToggle} onRemove={onRemoveBlock} onEdit={onEditMeal} />
              <DaySummaryFooter blocks={blocks} />
            </div>
          </div>

          {/* right rail: compact insight + weekly plan */}
          <aside className="col-span-12 space-y-4 md:space-y-6 xl:col-span-4">
            <InsightCard blocks={blocks} doneIds={doneIds} ach={ach} />
            <WeeklyPlanCard today={state.day} routine={routine} onAddRoutine={(day) => onAdd({ mode: "routine", day })} onRemoveRoutine={onRemoveRoutine} onDownload={onDownloadWeek} />
          </aside>
        </div>
      </Stagger>

      <Stagger i={3}><MealPlanBuilder onUseDay={onUseMealPlanDay} /></Stagger>

      <Stagger i={4}>
        <Heading label="Eat well" title="Recipes for you" action={<span className="text-[11px] text-[#0f3a26]/40">scroll for more</span>} />
        <RecipeRail onOpen={onOpenRecipe} />
      </Stagger>
    </div>
  );
}

function ActiveHeader({ state, onAdd, onBrowse, onReset }: { state: PlanState; onAdd: () => void; onBrowse: () => void; onReset: () => void }) {
  return (
    <div className={`${CARD} flex flex-col gap-4 p-5 md:flex-row md:items-center md:justify-between md:p-6`}>
      <div className="flex items-center gap-4">
        <span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#006E42] text-white"><CheckCircle2 className="h-6 w-6" /></span>
        <div>
          <h1 className="text-[17px] font-bold tracking-tight text-[#0f3a26]">Your plan is active</h1>
          <p className="mt-0.5 inline-flex items-center gap-1.5 text-[11.5px] text-[#0f3a26]/55"><FileText className="h-3.5 w-3.5" />From {state.fileName ?? "your report"}</p>
        </div>
      </div>
      <div className="flex items-center gap-3">
        <div className="flex items-center gap-1.5">
          {Array.from({ length: 7 }).map((_, i) => <span key={i} className={`h-2 rounded-full transition-all ${i < state.day ? "w-5 bg-[#006E42]" : "w-2 bg-[#0f3a26]/12"}`} />)}
        </div>
        <span className="text-[11.5px] font-semibold text-[#0f3a26]/60">Day {state.day} of 7</span>
      </div>
      <div className="flex flex-wrap items-center gap-2">
        <button onClick={onAdd} className="inline-flex items-center gap-1.5 rounded-xl bg-[#006E42] px-3.5 py-2 text-[12.5px] font-semibold text-white transition hover:bg-[#005634]"><Plus className="h-3.5 w-3.5" />Add event</button>
        <button onClick={onBrowse} className="inline-flex items-center gap-1.5 rounded-xl bg-white px-3 py-2 text-[12.5px] font-medium text-[#0f3a26]/65 ring-1 ring-inset ring-[#0f3a26]/10 transition hover:text-[#0f3a26]"><Upload className="h-3.5 w-3.5" />New</button>
        <button onClick={onReset} className="inline-flex items-center gap-1.5 rounded-xl bg-white px-3 py-2 text-[12.5px] font-medium text-[#0f3a26]/65 ring-1 ring-inset ring-[#0f3a26]/10 transition hover:text-[#0f3a26]"><RefreshCw className="h-3.5 w-3.5" />Reset</button>
      </div>
    </div>
  );
}

function DayTimeline({ blocks, doneIds, onToggle, onRemove, onEdit }: { blocks: DayBlock[]; doneIds: string[]; onToggle: (id: string) => void; onRemove: (id: string) => void; onEdit: (b: DayBlock) => void }) {
  const reduce = useReducedMotion();
  if (blocks.length === 0) return <p className="rounded-2xl bg-[#f1f7f3] p-8 text-center text-[12.5px] text-[#0f3a26]/55 ring-1 ring-inset ring-[#0f3a26]/[0.08]">No blocks left. Use Add to build your day.</p>;
  const groups = DAY_PARTS.map((p) => ({ ...p, items: blocks.filter((b) => partOfDay(b.time) === p.key) })).filter((g) => g.items.length);
  return (
    <div className="space-y-5">
      {groups.map((g) => {
        const doneN = g.items.filter((b) => doneIds.includes(b.id)).length;
        const all = doneN === g.items.length;
        return (
          <div key={g.key}>
            <div className="mb-2.5 flex items-center gap-2.5">
              <span className={`grid h-7 w-7 shrink-0 place-items-center rounded-lg ${all ? "bg-[#006E42] text-white" : "bg-[#006E42]/8 text-[#006E42]"}`}><g.icon className="h-4 w-4" /></span>
              <p className="text-[11px] font-bold uppercase tracking-[0.16em] text-[#0f3a26]/55">{g.label}</p>
              <span className="rounded-full bg-[#0f3a26]/6 px-2 py-0.5 text-[10px] font-semibold tabular-nums text-[#0f3a26]/50">{doneN}/{g.items.length}</span>
              <span className="h-px flex-1 bg-[#0f3a26]/8" />
            </div>
            <ul className="space-y-2">
              <AnimatePresence initial={false}>
                {g.items.map((b) => (
                  <BlockRow key={b.id} b={b} done={doneIds.includes(b.id)} onToggle={onToggle} onRemove={onRemove} onEdit={onEdit} reduce={!!reduce} />
                ))}
              </AnimatePresence>
            </ul>
          </div>
        );
      })}
    </div>
  );
}

function BlockRow({ b, done, onToggle, onRemove, onEdit, reduce }: { b: DayBlock; done: boolean; onToggle: (id: string) => void; onRemove: (id: string) => void; onEdit: (b: DayBlock) => void; reduce: boolean }) {
  const meta = BLOCK_META[b.type];
  const editable = b.type === "meal" || b.type === "snack";
  return (
    <motion.li layout initial={reduce ? false : { opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, x: -8 }} transition={{ duration: 0.28, ease: EASE }} className="flex items-center gap-2">
      <div onClick={() => onToggle(b.id)} role="button" tabIndex={0} onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); onToggle(b.id); } }} className={`flex min-w-0 flex-1 cursor-pointer items-center gap-3 rounded-2xl p-3 text-left ring-1 ring-inset transition ${done ? "bg-[#006E42]/[0.05] ring-[#006E42]/15" : "bg-[#f1f7f3] ring-[#0f3a26]/[0.08] hover:ring-[#006E42]/25 hover:shadow-[0_6px_16px_-10px_rgba(15,58,38,0.28)]"}`}>
        <span className={`hidden h-9 w-9 shrink-0 place-items-center rounded-xl transition-colors sm:grid ${done ? "bg-[#006E42] text-white" : meta.tint}`}>{done ? <Check className="h-4 w-4" /> : <meta.icon className="h-4 w-4" />}</span>
        <div className="min-w-0 flex-1">
          <div className="flex flex-col sm:flex-row sm:items-baseline sm:gap-2">
            <span className={`shrink-0 text-[11px] font-bold tabular-nums ${done ? "text-[#0f3a26]/40" : "text-[#006E42]"}`}>{b.time || "Anytime"}</span>
            <span className={`min-w-0 line-clamp-2 text-[13px] font-semibold leading-snug sm:truncate ${done ? "text-[#0f3a26]/50 line-through" : "text-[#0f3a26]"}`}>{b.title}</span>
            {b.custom && <span className="shrink-0 rounded-full bg-[#c79a3d]/15 px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-wide text-[#9c7426]">added</span>}
          </div>
          <p className="mt-0.5 line-clamp-2 text-[11px] text-[#0f3a26]/55 sm:truncate">{b.detail || TYPE_LABEL[b.type]}{b.kcal ? ` · ${b.kcal} kcal` : ""}</p>
        </div>
        {editable && <button onClick={(e) => { e.stopPropagation(); onEdit(b); }} aria-label="Adjust meal" className="grid h-8 w-8 shrink-0 place-items-center rounded-lg text-[#0f3a26]/40 ring-1 ring-inset ring-[#0f3a26]/12 transition hover:bg-white hover:text-[#006E42] hover:ring-[#006E42]/35"><Pencil className="h-4 w-4" /></button>}
      </div>
      <div className="flex shrink-0 items-center gap-1.5">
        <button onClick={() => onToggle(b.id)} aria-label={done ? "Mark not done" : "Mark done"} className={`grid h-8 w-8 place-items-center rounded-lg ring-1 ring-inset transition ${done ? "bg-[#006E42] text-white ring-[#006E42]" : "text-transparent ring-[#0f3a26]/20 hover:ring-[#006E42]/40"}`}><Check className="h-4 w-4" /></button>
        <button onClick={() => onRemove(b.id)} aria-label="Remove block" className="grid h-8 w-8 place-items-center rounded-lg text-[#0f3a26]/45 ring-1 ring-inset ring-[#0f3a26]/12 transition hover:text-[#c14040] hover:ring-[#c14040]/35"><Trash2 className="h-4 w-4" /></button>
      </div>
    </motion.li>
  );
}

function DaySummaryFooter({ blocks }: { blocks: DayBlock[] }) {
  const meals = blocks.filter((b) => b.type === "meal" || b.type === "snack").length;
  const workouts = blocks.filter((b) => b.type === "workout").length;
  const kcal = blocks.filter((b) => b.type === "meal" || b.type === "snack").reduce((s, b) => s + (b.kcal ?? 0), 0);
  const tiles = [
    { icon: Utensils, value: meals, label: "meals & snacks" },
    { icon: Dumbbell, value: workouts, label: "workouts" },
    { icon: Flame, value: kcal.toLocaleString(), label: "kcal planned" },
  ];
  return (
    <div className="mt-5 grid grid-cols-3 gap-2 border-t border-[#0f3a26]/8 pt-5 sm:gap-3">
      {tiles.map((t) => (
        <div key={t.label} className="rounded-2xl bg-[#f1f7f3] p-3 text-center ring-1 ring-inset ring-[#0f3a26]/[0.08]">
          <t.icon className="mx-auto h-4 w-4 text-[#006E42]" />
          <p className="mt-1.5 text-[17px] font-bold tabular-nums leading-none text-[#0f3a26]">{t.value}</p>
          <p className="mt-1 text-[10px] text-[#0f3a26]/50">{t.label}</p>
        </div>
      ))}
    </div>
  );
}

type InsightTab = "today" | "week";

function InsightCard({ blocks, doneIds, ach }: { blocks: DayBlock[]; doneIds: string[]; ach: Achievements | null }) {
  const reduce = useReducedMotion();
  const [tab, setTab] = useState<InsightTab>("today");
  const [dir, setDir] = useState(1);
  function go(next: InsightTab) {
    if (next === tab) return;
    setDir(next === "week" ? 1 : -1);
    setTab(next);
  }
  const TABS: { key: InsightTab; label: string }[] = [{ key: "today", label: "Today" }, { key: "week", label: "Weekly report" }];

  return (
    <div className={`${CARD} p-6`}>
      {/* segmented toggle */}
      <div className="grid grid-cols-2 gap-1 rounded-xl bg-[#f1f7f3] p-1 ring-1 ring-inset ring-[#0f3a26]/[0.08]">
        {TABS.map((t) => (
          <button key={t.key} onClick={() => go(t.key)} className={`relative rounded-lg py-1.5 text-[12px] font-semibold transition ${tab === t.key ? "text-[#0f3a26]" : "text-[#0f3a26]/50 hover:text-[#0f3a26]/75"}`}>
            {tab === t.key && <motion.span layoutId="insightTab" className="absolute inset-0 rounded-lg bg-white shadow-sm ring-1 ring-[#0f3a26]/8" transition={{ duration: 0.25, ease: EASE }} />}
            <span className="relative">{t.label}</span>
          </button>
        ))}
      </div>

      {/* sliding panels */}
      <div className="relative mt-5 min-h-[224px] overflow-hidden">
        <AnimatePresence custom={dir} mode="wait" initial={false}>
          <motion.div
            key={tab}
            custom={dir}
            initial={reduce ? false : { opacity: 0, x: dir * 44 }}
            animate={{ opacity: 1, x: 0 }}
            exit={reduce ? { opacity: 0 } : { opacity: 0, x: -dir * 44 }}
            transition={{ duration: 0.28, ease: EASE }}
            className="absolute inset-0 flex flex-col justify-center"
          >
            {tab === "today" ? <TodayPanel blocks={blocks} doneIds={doneIds} /> : <WeekPanel ach={ach} />}
          </motion.div>
        </AnimatePresence>
      </div>

      {/* dots */}
      <div className="mt-4 flex items-center justify-center gap-1.5">
        {TABS.map((t) => <span key={t.key} className={`h-1.5 rounded-full transition-all ${tab === t.key ? "w-5 bg-[#006E42]" : "w-1.5 bg-[#0f3a26]/15"}`} />)}
      </div>
    </div>
  );
}

function TodayPanel({ blocks, doneIds }: { blocks: DayBlock[]; doneIds: string[] }) {
  const done = blocks.filter((b) => doneIds.includes(b.id));
  const pct = blocks.length ? done.length / blocks.length : 0;
  const kcalDone = done.filter((b) => b.type === "meal" || b.type === "snack").reduce((s, b) => s + (b.kcal ?? 0), 0);
  const next = blocks.find((b) => !doneIds.includes(b.id));
  const NextIcon = next ? BLOCK_META[next.type].icon : CheckCircle2;
  return (
    <div>
      <div className="flex items-center gap-5">
        <ProgressRing pct={pct} />
        <div className="space-y-0.5">
          <p className="text-[13.5px] font-semibold text-[#0f3a26]">{done.length} of {blocks.length} done</p>
          <p className="text-[11.5px] text-[#0f3a26]/55">today&apos;s plan</p>
          <p className="mt-2 inline-flex items-center gap-1 text-[13.5px] font-bold tabular-nums text-[#0f3a26]"><Flame className="h-4 w-4 text-[#c79a3d]" />{kcalDone}<span className="text-[11px] font-normal text-[#0f3a26]/50">/{DAY_CALORIE_TARGET} kcal</span></p>
        </div>
      </div>
      <div className="mt-6 rounded-2xl bg-[#f1f7f3] p-4 ring-1 ring-inset ring-[#0f3a26]/[0.08]">
        <p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#0f3a26]/45">{next ? "Next up" : "All done"}</p>
        {next ? (
          <div className="mt-1.5 flex items-center gap-2.5">
            <span className="grid h-8 w-8 place-items-center rounded-lg bg-white text-[#006E42] ring-1 ring-inset ring-[#0f3a26]/8"><NextIcon className="h-4 w-4" /></span>
            <div className="min-w-0 flex-1"><p className="truncate text-[12.5px] font-semibold text-[#0f3a26]">{next.title}</p><p className="inline-flex items-center gap-1 text-[10.5px] text-[#0f3a26]/55"><Clock className="h-3 w-3" />{next.time || "Anytime"}</p></div>
          </div>
        ) : <p className="mt-1.5 inline-flex items-center gap-1.5 text-[12.5px] font-semibold text-[#006E42]"><CheckCircle2 className="h-4 w-4" />Every block complete. Nice work.</p>}
      </div>
    </div>
  );
}

function WeekPanel({ ach }: { ach: Achievements | null }) {
  if (!ach) return <div className="h-32 animate-pulse rounded-2xl bg-[#f1f7f3]" />;
  const bars = [
    { label: "Workouts", value: `${ach.workoutsDone}/${ach.workoutsTarget}`, pct: ach.workoutsDone / ach.workoutsTarget },
    { label: "Active minutes", value: `${ach.activeMinutes}/${ach.activeTarget}`, pct: ach.activeMinutes / ach.activeTarget },
    { label: "Hydration", value: `${ach.hydrationPct}%`, pct: ach.hydrationPct / 100 },
  ];
  return (
    <div>
      <div className="flex items-center justify-between">
        <div>
          <p className="text-[30px] font-bold leading-none tabular-nums text-[#0f3a26]">{ach.adherencePct}%</p>
          <p className="mt-1 text-[11px] text-[#0f3a26]/55">on plan this week</p>
        </div>
        <span className="inline-flex items-center gap-1.5 rounded-full bg-[#c79a3d]/[0.10] px-3 py-1.5 text-[12px] font-semibold text-[#9c7426] ring-1 ring-inset ring-[#c79a3d]/20"><Flame className="h-3.5 w-3.5" />{ach.streakDays} day streak</span>
      </div>
      <div className="mt-5 space-y-4 border-t border-[#0f3a26]/8 pt-5">
        {bars.map((b) => <Bar key={b.label} label={b.label} value={b.value} pct={b.pct} />)}
      </div>
    </div>
  );
}

function Bar({ label, value, pct }: { label: string; value: string; pct: number }) {
  const reduce = useReducedMotion();
  return (
    <div>
      <div className="mb-1 flex items-center justify-between text-[11.5px]"><span className="font-medium text-[#0f3a26]/70">{label}</span><span className="tabular-nums font-semibold text-[#0f3a26]">{value}</span></div>
      <div className="h-1.5 w-full overflow-hidden rounded-full bg-[#0f3a26]/8"><motion.div className="h-full rounded-full bg-[#006E42]" initial={reduce ? false : { width: 0 }} animate={{ width: `${Math.min(100, pct * 100)}%` }} transition={{ duration: 0.8, ease: EASE }} /></div>
    </div>
  );
}

function ProgressRing({ pct }: { pct: number }) {
  const R = 40; const C = 2 * Math.PI * R; const reduce = useReducedMotion();
  return (
    <div className="relative grid h-24 w-24 shrink-0 place-items-center">
      <svg className="h-24 w-24 -rotate-90" viewBox="0 0 100 100">
        <circle cx="50" cy="50" r={R} fill="none" stroke="#0f3a26" strokeOpacity="0.08" strokeWidth="9" />
        <motion.circle cx="50" cy="50" r={R} fill="none" stroke="#006E42" strokeWidth="9" strokeLinecap="round" strokeDasharray={C} initial={reduce ? false : { strokeDashoffset: C }} animate={{ strokeDashoffset: C * (1 - pct) }} transition={{ duration: 0.9, ease: EASE }} />
      </svg>
      <p className="absolute text-[20px] font-bold tabular-nums text-[#0f3a26]">{Math.round(pct * 100)}%</p>
    </div>
  );
}

function WeeklyPlanCard({ today, routine, onAddRoutine, onRemoveRoutine, onDownload }: { today: number; routine: RoutineItem[]; onAddRoutine: (day: string) => void; onRemoveRoutine: (id: string) => void; onDownload: () => void }) {
  const [open, setOpen] = useState(WEEK_PLAN[Math.min(Math.max(today - 1, 0), WEEK_PLAN.length - 1)].key);
  return (
    <div className={`${CARD} p-5 md:p-6`}>
      <div className="mb-3 flex items-center justify-between">
        <h2 className="text-[15px] font-bold tracking-tight text-[#0f3a26]">This week</h2>
        <button onClick={onDownload} className="inline-flex items-center gap-1.5 rounded-lg bg-[#f1f7f3] px-2.5 py-1.5 text-[11.5px] font-semibold text-[#0f3a26]/70 ring-1 ring-inset ring-[#0f3a26]/[0.08] transition hover:text-[#006E42]"><Download className="h-3.5 w-3.5" />PDF</button>
      </div>
      <ul className="divide-y divide-[#0f3a26]/8">
        {WEEK_PLAN.map((d, i) => {
          const isOpen = open === d.key; const isToday = i === today - 1; const extras = routine.filter((r) => r.day === d.key);
          return (
            <li key={d.key}>
              <button onClick={() => setOpen(isOpen ? "" : d.key)} className="flex w-full items-center gap-3 py-2.5 text-left">
                <span className={`grid h-8 w-9 shrink-0 place-items-center rounded-lg text-[11px] font-bold uppercase ${isToday ? "bg-[#006E42] text-white" : "bg-[#f1f7f3] text-[#0f3a26]/60 ring-1 ring-inset ring-[#0f3a26]/[0.08]"}`}>{d.short}</span>
                <div className="min-w-0 flex-1"><p className="truncate text-[12.5px] font-semibold text-[#0f3a26]">{d.focus}</p><p className="text-[10.5px] text-[#0f3a26]/50">{d.kcal} kcal target{extras.length ? ` · +${extras.length} added` : ""}</p></div>
                <ChevronDown className={`h-4 w-4 shrink-0 text-[#0f3a26]/35 transition ${isOpen ? "rotate-180" : ""}`} />
              </button>
              <AnimatePresence initial={false}>
                {isOpen && (
                  <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.2 }} className="pb-3 pl-12">
                    <div className="flex flex-wrap gap-1.5">
                      {d.items.map((it) => <span key={it} className="inline-flex items-center gap-1 rounded-full bg-[#f1f7f3] px-2.5 py-1 text-[11px] font-medium text-[#0f3a26]/70 ring-1 ring-inset ring-[#0f3a26]/[0.08]"><Check className="h-3 w-3 text-[#006E42]" />{it}</span>)}
                      {extras.map((r) => (
                        <span key={r.id} className="group inline-flex items-center gap-1 rounded-full bg-[#006E42]/8 px-2.5 py-1 text-[11px] font-medium text-[#006E42] ring-1 ring-inset ring-[#006E42]/20">
                          {r.kind === "exercise" ? <Dumbbell className="h-3 w-3" /> : <Utensils className="h-3 w-3" />}{r.label}
                          <button onClick={() => onRemoveRoutine(r.id)} aria-label="Remove" className="text-[#006E42]/50 hover:text-[#c14040]"><X className="h-3 w-3" /></button>
                        </span>
                      ))}
                      <button onClick={() => onAddRoutine(d.key)} className="inline-flex items-center gap-1 rounded-full border border-dashed border-[#0f3a26]/20 px-2.5 py-1 text-[11px] font-semibold text-[#0f3a26]/55 transition hover:border-[#006E42]/40 hover:text-[#006E42]"><Plus className="h-3 w-3" />Add to routine</button>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </li>
          );
        })}
      </ul>
    </div>
  );
}

/* ============================================================= RECIPES ==== */

function RecipeRail({ onOpen }: { onOpen: (r: Meal) => void }) {
  const reduce = useReducedMotion();
  const scroller = useRef<HTMLDivElement>(null);
  const [edges, setEdges] = useState({ left: false, right: true });
  const [meals, setMeals] = useState<Meal[] | null>(null);
  const [diet, setDiet] = useState<"all" | Diet>("all");

  useEffect(() => { fetchMeals().then(setMeals); }, []);

  function update() {
    const el = scroller.current;
    if (!el) return;
    setEdges({ left: el.scrollLeft > 8, right: el.scrollLeft < el.scrollWidth - el.clientWidth - 8 });
  }
  useEffect(() => {
    update();
    const el = scroller.current;
    if (!el) return;
    window.addEventListener("resize", update);
    return () => window.removeEventListener("resize", update);
  }, [meals, diet]);
  const scrollBy = (dir: number) => scroller.current?.scrollBy({ left: dir * 340, behavior: "smooth" });

  const available = new Set((meals ?? []).map((m) => m.diet));
  const chips = DIETS.filter((d) => available.has(d.key));
  const shown = (meals ?? []).filter((m) => diet === "all" || m.diet === diet);

  if (meals && meals.length === 0) {
    return <div className="rounded-2xl bg-[#f1f7f3] px-4 py-8 text-center text-[13px] text-[#0f3a26]/55 ring-1 ring-inset ring-[#0f3a26]/[0.06]">No meal suggestions yet.</div>;
  }

  return (
    <div>
      {/* diet filter */}
      {chips.length > 0 && (
        <div className="mb-3 flex flex-wrap items-center gap-1.5">
          <button onClick={() => setDiet("all")} className={`rounded-full px-3 py-1 text-[12px] font-semibold transition ${diet === "all" ? "bg-[#006E42] text-white" : "bg-white text-[#0f3a26]/65 ring-1 ring-[#0f3a26]/10 hover:ring-[#006E42]/30"}`}>All</button>
          {chips.map((d) => (
            <button key={d.key} onClick={() => setDiet(d.key)} className={`rounded-full px-3 py-1 text-[12px] font-semibold transition ${diet === d.key ? "bg-[#006E42] text-white" : "bg-white text-[#0f3a26]/65 ring-1 ring-[#0f3a26]/10 hover:ring-[#006E42]/30"}`}>{d.short}</button>
          ))}
        </div>
      )}

      <div className="relative">
        <div ref={scroller} onScroll={update} className="no-scrollbar -mx-1 flex snap-x snap-mandatory gap-5 overflow-x-auto px-1 pb-2">
        {!meals
          ? Array.from({ length: 4 }).map((_, i) => <div key={i} className={`h-[268px] w-[300px] shrink-0 animate-pulse ${CARD}`} />)
          : shown.map((r, i) => {
              const dm = DIET_META[r.diet];
              const hasVideo = !!youtubeId(r.youtubeUrl);
              return (
                <motion.button
                  key={r.id}
                  onClick={() => onOpen(r)}
                  initial={reduce ? false : { opacity: 0, y: 12 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.4, ease: EASE, delay: reduce ? 0 : Math.min(i, 6) * 0.05 }}
                  className={`group w-[300px] shrink-0 snap-start overflow-hidden text-left ${CARD} transition hover:ring-[#006E42]/30`}
                >
                  <div className="relative h-44 overflow-hidden">
                    <span className="absolute inset-0 bg-cover bg-center transition-transform duration-500 group-hover:scale-105" style={{ backgroundImage: `url(${r.image})` }} aria-hidden />
                    <span className="absolute left-3 top-3 rounded-full bg-white/90 px-2.5 py-1 text-[10.5px] font-semibold text-[#006E42] backdrop-blur">{r.tag}</span>
                    <span className={`absolute left-3 bottom-3 rounded-full px-2 py-0.5 text-[10px] font-semibold ${dm.cls}`}>{dm.short}</span>
                    {hasVideo && <span className="absolute right-3 top-3 inline-flex items-center gap-1 rounded-full bg-black/55 px-2 py-0.5 text-[10px] font-semibold text-white backdrop-blur-sm"><Film className="h-3 w-3" />Video</span>}
                    <span className="absolute bottom-3 right-3 inline-flex items-center gap-1 rounded-full bg-white/90 px-2.5 py-1 text-[10.5px] font-semibold text-[#0f3a26] backdrop-blur"><Timer className="h-3 w-3" />{r.timeMins}m</span>
                  </div>
                  <div className="p-4">
                    <p className="line-clamp-1 text-[14.5px] font-bold text-[#0f3a26]">{r.name}</p>
                    <div className="mt-2 flex items-center gap-3 text-[12px] text-[#0f3a26]/60">
                      <span className="inline-flex items-center gap-1"><Flame className="h-3.5 w-3.5 text-[#c79a3d]" />{r.kcal}</span>
                      <span className="inline-flex items-center gap-1"><Dumbbell className="h-3.5 w-3.5 text-[#006E42]" />{r.protein}g</span>
                      <span className="ml-auto inline-flex items-center gap-1 font-semibold text-[#006E42]">Recipe<ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-0.5" /></span>
                    </div>
                  </div>
                </motion.button>
              );
            })}
        </div>

        {/* scroll arrows */}
        <button
          onClick={() => scrollBy(-1)}
          aria-label="Scroll left"
          className={`absolute left-1 top-[88px] hidden h-9 w-9 -translate-y-1/2 place-items-center rounded-full bg-white text-[#0f3a26] shadow-[0_6px_16px_-6px_rgba(15,58,38,0.4)] ring-1 ring-[#0f3a26]/10 transition hover:text-[#006E42] sm:grid ${edges.left ? "opacity-100" : "pointer-events-none opacity-0"}`}
        >
          <ChevronLeft className="h-4 w-4" />
        </button>
        <button
          onClick={() => scrollBy(1)}
          aria-label="Scroll right"
          className={`absolute right-1 top-[88px] hidden h-9 w-9 -translate-y-1/2 place-items-center rounded-full bg-white text-[#0f3a26] shadow-[0_6px_16px_-6px_rgba(15,58,38,0.4)] ring-1 ring-[#0f3a26]/10 transition hover:text-[#006E42] sm:grid ${edges.right ? "opacity-100" : "pointer-events-none opacity-0"}`}
        >
          <ChevronRight className="h-4 w-4" />
        </button>
      </div>
    </div>
  );
}

function RecipeModal({ recipe, onClose, onLog, canLog }: { recipe: Meal | null; onClose: () => void; onLog: (r: Meal) => void; canLog: boolean }) {
  const reduce = useReducedMotion();
  const [videoFor, setVideoFor] = useState<Meal | null>(null);
  const showVideo = videoFor !== null && videoFor === recipe;
  useEffect(() => {
    if (!recipe) return;
    const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); };
    window.addEventListener("keydown", onKey);
    document.body.style.overflow = "hidden";
    return () => { window.removeEventListener("keydown", onKey); document.body.style.overflow = ""; };
  }, [recipe, onClose]);

  const vid = youtubeId(recipe?.youtubeUrl);
  const dm = recipe ? DIET_META[recipe.diet] : null;

  return (
    <AnimatePresence>
      {recipe && (
        <motion.div className="fixed inset-0 z-50 flex items-end justify-center p-4 sm:items-center" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.2 }}>
          <div className="absolute inset-0 bg-[#0f3a26]/45" onClick={onClose} aria-hidden />
          <motion.div role="dialog" aria-modal="true" aria-label={recipe.name} className={`relative flex max-h-[86vh] w-full max-w-lg flex-col ${CARD} overflow-hidden`} initial={reduce ? false : { opacity: 0, y: 20, scale: 0.98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={reduce ? { opacity: 0 } : { opacity: 0, y: 12, scale: 0.98 }} transition={{ duration: 0.3, ease: EASE }}>
            {showVideo && vid ? (
              <div className="relative aspect-video w-full shrink-0 bg-black">
                <iframe src={`https://www.youtube-nocookie.com/embed/${vid}?autoplay=1&rel=0`} title={recipe.name} className="h-full w-full" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowFullScreen />
                <button onClick={() => setVideoFor(null)} aria-label="Back to photo" className="absolute right-3 top-3 grid h-8 w-8 place-items-center rounded-lg bg-white/85 text-[#0f3a26] backdrop-blur transition hover:bg-white"><X className="h-4 w-4" /></button>
              </div>
            ) : (
              <div className="relative h-44 shrink-0">
                <span className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: `url(${recipe.image})` }} aria-hidden />
                <div className="absolute inset-0 bg-gradient-to-t from-[#0f3a26]/70 to-transparent" />
                <button onClick={onClose} aria-label="Close" className="absolute right-3 top-3 grid h-8 w-8 place-items-center rounded-lg bg-white/85 text-[#0f3a26] backdrop-blur transition hover:bg-white"><X className="h-4 w-4" /></button>
                {vid && (
                  <button onClick={() => setVideoFor(recipe)} aria-label="Play recipe video" className="absolute left-1/2 top-1/2 inline-flex -translate-x-1/2 -translate-y-1/2 items-center gap-2 rounded-full bg-white/90 px-4 py-2 text-[12.5px] font-semibold text-[#0f3a26] shadow-lg backdrop-blur transition hover:bg-white">
                    <span className="grid h-6 w-6 place-items-center rounded-full bg-[#006E42] text-white"><Play className="h-3 w-3 translate-x-[1px] fill-current" /></span>
                    Watch recipe
                  </button>
                )}
                <div className="absolute bottom-3 left-4 right-4">
                  <div className="flex items-center gap-1.5">
                    <span className="rounded-full bg-white/90 px-2.5 py-1 text-[10.5px] font-semibold text-[#006E42]">{recipe.tag}</span>
                    {dm && <span className={`rounded-full px-2 py-1 text-[10.5px] font-semibold ${dm.cls}`}>{dm.short}</span>}
                  </div>
                  <h2 className="mt-1.5 text-[19px] font-bold text-white">{recipe.name}</h2>
                </div>
              </div>
            )}

            <div className="no-scrollbar flex-1 overflow-y-auto p-5">
              <div className="flex flex-wrap gap-2">
                {[{ i: Flame, t: `${recipe.kcal} kcal`, c: "text-[#c79a3d]" }, { i: Dumbbell, t: `${recipe.protein}g protein`, c: "text-[#006E42]" }, { i: Timer, t: `${recipe.timeMins} min`, c: "text-[#0f3a26]/45" }, { i: Utensils, t: `${recipe.servings} serving${recipe.servings > 1 ? "s" : ""}`, c: "text-[#0f3a26]/45" }].map((m, k) => (
                  <span key={k} className="inline-flex items-center gap-1.5 rounded-lg bg-[#f1f7f3] px-2.5 py-1.5 text-[11.5px] font-semibold text-[#0f3a26] ring-1 ring-inset ring-[#0f3a26]/[0.08]"><m.i className={`h-3.5 w-3.5 ${m.c}`} />{m.t}</span>
                ))}
              </div>

              {recipe.description && <p className="mt-4 text-[13px] leading-relaxed text-[#0f3a26]/70">{recipe.description}</p>}

              {vid && !showVideo && (
                <button onClick={() => setVideoFor(recipe)} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#c14040]/8 px-3.5 py-2 text-[12.5px] font-semibold text-[#c14040] transition hover:bg-[#c14040]/12"><Film className="h-3.5 w-3.5" />Watch the recipe video</button>
              )}

              <div className="mt-5">
                <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-[#006E42]/70">Ingredients</p>
                <ul className="mt-2 grid grid-cols-1 gap-1.5 sm:grid-cols-2">
                  {recipe.ingredients.map((ing, k) => <li key={k} className="flex items-start gap-2 text-[12.5px] text-[#0f3a26]/75"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[#006E42]" />{ing}</li>)}
                </ul>
              </div>

              <div className="mt-5">
                <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-[#006E42]/70">Steps</p>
                <ol className="mt-2 space-y-2.5">
                  {recipe.steps.map((st, k) => (
                    <li key={k} className="flex gap-3">
                      <span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-[#006E42] text-[11px] font-bold text-white">{k + 1}</span>
                      <p className="pt-0.5 text-[12.5px] leading-relaxed text-[#0f3a26]/75">{st}</p>
                    </li>
                  ))}
                </ol>
              </div>
            </div>

            {canLog && (
              <div className="border-t border-[#0f3a26]/8 p-4">
                <button onClick={() => onLog(recipe)} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#006E42] px-4 py-2.5 text-[13px] font-semibold text-white transition hover:bg-[#005634]"><Plus className="h-4 w-4" />Log this meal to today</button>
              </div>
            )}
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

/* ============================================================= ADD EVENT === */

type AddType = "food" | "snack" | "exercise";

function AddEventModal({ init, onClose, onAddDay, onAddRoutine }: { init: AddInit | null; onClose: () => void; onAddDay: (b: Omit<DayBlock, "id" | "custom">) => void; onAddRoutine: (r: { days: string[]; label: string; kind: RoutineItem["kind"] }) => void }) {
  const reduce = useReducedMotion();
  const [mode, setMode] = useState<"today" | "routine">("today");
  const [type, setType] = useState<AddType>("food");
  const [title, setTitle] = useState("");
  const [time, setTime] = useState("");
  const [kcal, setKcal] = useState("");
  const [days, setDays] = useState<string[]>([]);

  // Reset the form each time the modal is opened with a new request.
  const [seenInit, setSeenInit] = useState<AddInit | null>(null);
  if (init && init !== seenInit) {
    setSeenInit(init);
    setMode(init.mode); setDays([init.day]); setType("food"); setTitle(""); setTime(init.time ?? ""); setKcal("");
  }

  useEffect(() => {
    if (!init) return;
    const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [init, onClose]);

  const toggleDay = (k: string) => setDays((cur) => (cur.includes(k) ? cur.filter((d) => d !== k) : [...cur, k]));
  const blockType: BlockType = type === "exercise" ? "workout" : type === "snack" ? "snack" : "meal";
  const valid = title.trim().length > 1 && (mode === "today" || days.length > 0);

  function save() {
    if (!valid) return;
    if (mode === "today") {
      onAddDay({ time: time.trim(), type: blockType, title: title.trim(), detail: "", kcal: kcal ? Number(kcal) : undefined });
    } else {
      onAddRoutine({ days, label: title.trim(), kind: type === "exercise" ? "exercise" : "food" });
    }
  }

  return (
    <AnimatePresence>
      {init && (
        <motion.div className="fixed inset-0 z-50 flex items-end justify-center p-4 sm:items-center" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.2 }}>
          <div className="absolute inset-0 bg-[#0f3a26]/45" onClick={onClose} aria-hidden />
          <motion.div role="dialog" aria-modal="true" aria-label="Add event" className={`relative w-full max-w-md ${CARD} p-5`} initial={reduce ? false : { opacity: 0, y: 20, scale: 0.98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={reduce ? { opacity: 0 } : { opacity: 0, y: 12, scale: 0.98 }} transition={{ duration: 0.3, ease: EASE }}>
            <div className="flex items-center justify-between">
              <h2 className="text-[16px] font-bold tracking-tight text-[#0f3a26]">Add event</h2>
              <button onClick={onClose} aria-label="Close" className="grid h-8 w-8 place-items-center rounded-lg text-[#0f3a26]/50 transition hover:bg-[#0f3a26]/6 hover:text-[#0f3a26]"><X className="h-4 w-4" /></button>
            </div>

            {/* type */}
            <div className="mt-4">
              <p className="mb-1.5 text-[11px] font-semibold text-[#0f3a26]/60">Type</p>
              <div className="grid grid-cols-3 gap-1.5">
                {([["food", Utensils, "Food"], ["snack", Cookie, "Snack"], ["exercise", Dumbbell, "Exercise"]] as [AddType, React.ComponentType<{ className?: string }>, string][]).map(([v, Ic, lb]) => (
                  <button key={v} onClick={() => setType(v)} className={`inline-flex items-center justify-center gap-1.5 rounded-xl px-2 py-2 text-[12px] font-semibold transition ${type === v ? "bg-[#006E42] text-white" : "bg-[#f1f7f3] text-[#0f3a26]/65 ring-1 ring-inset ring-[#0f3a26]/[0.08] hover:text-[#0f3a26]"}`}><Ic className="h-3.5 w-3.5" />{lb}</button>
                ))}
              </div>
            </div>

            {/* name */}
            <label className="mt-3 block">
              <span className="mb-1.5 block text-[11px] font-semibold text-[#0f3a26]/60">Name</span>
              <input value={title} onChange={(e) => setTitle(e.target.value)} placeholder={type === "exercise" ? "e.g. 20 min evening walk" : "e.g. Grilled paneer"} className="w-full rounded-xl border border-[#0f3a26]/[0.14] bg-[#f6faf7] px-3.5 py-2.5 text-[13.5px] text-[#0f3a26] shadow-[inset_0_1px_2px_rgba(15,58,38,0.04)] placeholder:text-[#0f3a26]/30 focus:border-[#006E42]/40 focus:outline-none focus:ring-2 focus:ring-[#006E42]/15" />
            </label>

            {/* today-only fields */}
            {mode === "today" && (
              <div className="mt-3 grid grid-cols-2 gap-3">
                <label className="block">
                  <span className="mb-1.5 block text-[11px] font-semibold text-[#0f3a26]/60">Time <span className="font-normal text-[#0f3a26]/40">(optional)</span></span>
                  <input value={time} onChange={(e) => setTime(e.target.value)} placeholder="14:30" className="w-full rounded-xl border border-[#0f3a26]/[0.14] bg-[#f6faf7] px-3.5 py-2.5 text-[13.5px] text-[#0f3a26] shadow-[inset_0_1px_2px_rgba(15,58,38,0.04)] placeholder:text-[#0f3a26]/30 focus:border-[#006E42]/40 focus:outline-none focus:ring-2 focus:ring-[#006E42]/15" />
                </label>
                {type !== "exercise" && (
                  <label className="block">
                    <span className="mb-1.5 block text-[11px] font-semibold text-[#0f3a26]/60">Calories <span className="font-normal text-[#0f3a26]/40">(optional)</span></span>
                    <input value={kcal} onChange={(e) => setKcal(e.target.value.replace(/[^0-9]/g, ""))} inputMode="numeric" placeholder="320" className="w-full rounded-xl border border-[#0f3a26]/[0.14] bg-[#f6faf7] px-3.5 py-2.5 text-[13.5px] text-[#0f3a26] shadow-[inset_0_1px_2px_rgba(15,58,38,0.04)] placeholder:text-[#0f3a26]/30 focus:border-[#006E42]/40 focus:outline-none focus:ring-2 focus:ring-[#006E42]/15" />
                  </label>
                )}
              </div>
            )}

            {/* routine day picker (multi-select) */}
            {mode === "routine" && (
              <div className="mt-3">
                <div className="mb-1.5 flex items-center justify-between">
                  <p className="text-[11px] font-semibold text-[#0f3a26]/60">Which days <span className="font-normal text-[#0f3a26]/40">({days.length} selected)</span></p>
                  <div className="flex items-center gap-1.5 text-[10.5px] font-semibold text-[#006E42]">
                    <button onClick={() => setDays(WEEK_PLAN.map((d) => d.key))} className="hover:underline">All</button>
                    <span className="text-[#0f3a26]/20">·</span>
                    <button onClick={() => setDays(["mon", "tue", "wed", "thu", "fri"])} className="hover:underline">Weekdays</button>
                    <span className="text-[#0f3a26]/20">·</span>
                    <button onClick={() => setDays(["sat", "sun"])} className="hover:underline">Weekend</button>
                    <span className="text-[#0f3a26]/20">·</span>
                    <button onClick={() => setDays([])} className="text-[#0f3a26]/45 hover:underline">Clear</button>
                  </div>
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {WEEK_PLAN.map((d) => {
                    const on = days.includes(d.key);
                    return (
                      <button key={d.key} onClick={() => toggleDay(d.key)} className={`inline-flex items-center gap-1 rounded-lg px-2.5 py-1.5 text-[11.5px] font-semibold transition ${on ? "bg-[#006E42] text-white" : "bg-[#f1f7f3] text-[#0f3a26]/60 ring-1 ring-inset ring-[#0f3a26]/[0.08] hover:text-[#0f3a26]"}`}>
                        {on && <Check className="h-3 w-3" />}{d.short}
                      </button>
                    );
                  })}
                </div>
              </div>
            )}

            {/* save-to toggle (the two options) */}
            <div className="mt-4 rounded-2xl bg-[#f1f7f3] p-1 ring-1 ring-inset ring-[#0f3a26]/[0.08]">
              <div className="grid grid-cols-2 gap-1">
                <button onClick={() => setMode("today")} className={`rounded-xl px-3 py-2 text-[12.5px] font-semibold transition ${mode === "today" ? "bg-white text-[#0f3a26] shadow-sm ring-1 ring-[#0f3a26]/8" : "text-[#0f3a26]/55"}`}>Save for today</button>
                <button onClick={() => setMode("routine")} className={`rounded-xl px-3 py-2 text-[12.5px] font-semibold transition ${mode === "routine" ? "bg-white text-[#0f3a26] shadow-sm ring-1 ring-[#0f3a26]/8" : "text-[#0f3a26]/55"}`}>Make it routine</button>
              </div>
            </div>
            <p className="mt-2 text-[11px] text-[#0f3a26]/50">{mode === "today" ? "Adds this to today&apos;s plan only." : `Repeats every week on ${days.length || "the"} selected day${days.length === 1 ? "" : "s"}.`}</p>

            <button onClick={save} disabled={!valid} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#006E42] px-4 py-2.5 text-[13px] font-semibold text-white transition hover:bg-[#005634] disabled:opacity-45"><Plus className="h-4 w-4" />{mode === "today" ? "Add to today" : "Add to routine"}</button>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

/* ============================== Meal editor ============================== */

const fmtNum = (v: number) => (Number.isInteger(v) ? String(v) : v.toFixed(1));

type PortionInfo = {
  mode: "count" | "gram";
  unitSingular: string;
  unitPlural: string;
  byLabel: string;
  step: number;
  min: number;
  chips: number[];
  base: number;
  name: string;
  kcalAt: (v: number) => number;
  detailAt: (v: number) => string;
};

/* Work out how to portion the meal that is already planned: piece foods
   (eggs, rotis) step by count, weight foods (rice, chicken) step by grams,
   and anything composite steps by serving, scaling its existing calories. */
function analyzeMeal(block: DayBlock): PortionInfo {
  const detail = (block.detail || "").trim();
  const title = block.title || "meal";
  const matched = matchFood(detail);
  const leadCount = parseCount(detail);
  const gramAmt = parseGrams(detail);
  const short = detail.length > 0 && detail.length <= 16;
  const single = !!matched && (leadCount != null || gramAmt != null || short);

  if (single && matched && matched.piece) {
    const u = matched.pieceLabel || "piece";
    const per = matched.piece;
    return {
      mode: "count", unitSingular: u, unitPlural: `${u}s`, byLabel: `By ${u}`,
      step: 1, min: 1, chips: [1, 2, 3, 4], base: leadCount ?? 1, name: detail || title,
      kcalAt: (v) => Math.round((matched.kcal * v * per) / 100),
      detailAt: (v) => `${v} ${u}${v > 1 ? "s" : ""}`,
    };
  }
  if (single && matched) {
    return {
      mode: "gram", unitSingular: "g", unitPlural: "g", byLabel: "By weight",
      step: 25, min: 25, chips: [50, 100, 150, 200], base: gramAmt ?? 100, name: matched.name,
      kcalAt: (v) => Math.round((matched.kcal * v) / 100),
      detailAt: (v) => `${matched.name} · ${v} g`,
    };
  }
  const baseServ = leadCount ?? 1;
  const perServing = (block.kcal ?? 0) / Math.max(1, baseServ);
  const cleanName = detail.replace(/^\s*\d+\s*(?:servings?|x|×)?\s*/i, "").trim() || title;
  return {
    mode: "count", unitSingular: "serving", unitPlural: "servings", byLabel: "By serving",
    step: 0.5, min: 0.5, chips: [0.5, 1, 1.5, 2], base: baseServ, name: detail || title,
    kcalAt: (v) => Math.round(perServing * v),
    detailAt: (v) => (v === 1 ? detail || title : `${cleanName} · ${fmtNum(v)} servings`),
  };
}

function MealEditor({ block, onClose, onSave }: { block: DayBlock | null; onClose: () => void; onSave: (id: string, patch: Partial<Omit<DayBlock, "id">>) => void }) {
  const reduce = useReducedMotion();
  const [tab, setTab] = useState<"modify" | "choose">("modify");
  const [meals, setMeals] = useState<Meal[] | null>(null);
  const [filter, setFilter] = useState<string>("all");
  const [amount, setAmount] = useState(1);

  const info = useMemo(() => (block ? analyzeMeal(block) : null), [block]);

  // Start each opened meal fresh.
  const [seenBlock, setSeenBlock] = useState<DayBlock | null>(null);
  if (block && block !== seenBlock) {
    setSeenBlock(block);
    setTab("modify");
    setFilter("all");
    setAmount(analyzeMeal(block).base);
  }

  useEffect(() => {
    if (!block) return;
    fetchMeals().then(setMeals);
    const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); };
    window.addEventListener("keydown", onKey);
    document.body.style.overflow = "hidden";
    return () => { window.removeEventListener("keydown", onKey); document.body.style.overflow = ""; };
  }, [block, onClose]);

  const list = meals ?? [];
  const dietChips = DIETS.filter((d) => list.some((m) => m.diet === d.key));
  const cuisineChips = Array.from(new Set(list.map((m) => m.cuisine)));
  const shown = list.filter((m) => (filter === "all" ? true : filter.startsWith("cuisine:") ? m.cuisine === filter.slice(8) : m.diet === filter));

  const newKcal = info ? info.kcalAt(amount) : 0;
  const curKcal = block?.kcal ?? 0;
  const delta = newKcal - curKcal;
  const bump = (d: number) => setAmount((a) => Math.max(info?.min ?? 0, Math.round((a + d) * 100) / 100));

  function chooseMeal(m: Meal) {
    if (!block) return;
    onSave(block.id, { type: block.type === "snack" ? "snack" : "meal", detail: m.name, kcal: m.kcal });
  }
  function savePortion() {
    if (!block || !info) return;
    onSave(block.id, { type: block.type === "snack" ? "snack" : "meal", detail: info.detailAt(amount), kcal: newKcal });
  }

  const chipCls = (active: boolean) => `whitespace-nowrap rounded-full px-3.5 py-1.5 text-[12px] font-semibold transition ${active ? "bg-[#006E42] text-white shadow-sm" : "bg-white text-[#0f3a26]/60 ring-1 ring-inset ring-[#0f3a26]/10 hover:ring-[#006E42]/35"}`;
  const stepBtn = "grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-[#f1f7f3] text-[#0f3a26]/70 ring-1 ring-inset ring-[#0f3a26]/[0.08] transition hover:text-[#006E42] disabled:opacity-40";

  return (
    <AnimatePresence>
      {block && info && (
        <motion.div className="fixed inset-0 z-50 flex items-end justify-center p-3 sm:items-center sm:p-6" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.2 }}>
          <div className="absolute inset-0 bg-[#0f3a26]/50" onClick={onClose} aria-hidden />
          <motion.div role="dialog" aria-modal="true" aria-label="Adjust meal" className={`relative flex h-[88vh] w-full max-w-2xl flex-col overflow-hidden ${CARD} sm:h-[600px]`} initial={reduce ? false : { opacity: 0, y: 22, scale: 0.98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={reduce ? { opacity: 0 } : { opacity: 0, y: 14, scale: 0.98 }} transition={{ duration: 0.3, ease: EASE }}>
            {/* header */}
            <div className="flex shrink-0 items-start gap-3 border-b border-[#0f3a26]/8 px-5 py-4 sm:px-6 sm:py-5">
              <button onClick={onClose} aria-label="Back" className="mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-lg text-[#0f3a26]/55 transition hover:bg-[#0f3a26]/6 hover:text-[#0f3a26]"><ChevronLeft className="h-5 w-5" /></button>
              <div className="min-w-0 flex-1">
                <h2 className="text-[19px] font-bold leading-tight tracking-tight text-[#0f3a26] sm:text-[21px]">Adjust your meal</h2>
                <p className="mt-0.5 text-[12.5px] leading-snug text-[#0f3a26]/60">Change the portion of what is planned, or pick a different meal for this slot.</p>
              </div>
            </div>

            {/* tabs */}
            <div className="flex shrink-0 items-center gap-4 border-b border-[#0f3a26]/8 px-5 sm:px-6">
              {([["modify", "Modify the meal"], ["choose", "Choose a meal"]] as const).map(([k, label]) => (
                <button key={k} onClick={() => setTab(k)} className={`relative -mb-px border-b-2 py-2.5 text-[13px] font-semibold transition ${tab === k ? "border-[#006E42] text-[#006E42]" : "border-transparent text-[#0f3a26]/45 hover:text-[#0f3a26]/70"}`}>{label}</button>
              ))}
            </div>

            {/* body (fixed height, scrolls inside) */}
            <div className="min-h-0 flex-1">
              {tab === "modify" ? (
                <div className="no-scrollbar h-full overflow-y-auto p-5 sm:p-6">
                  <p className="text-[12.5px] leading-snug text-[#0f3a26]/60">This meal is already planned. Make the portion bigger or smaller and the calories update to match.</p>

                  {/* current meal */}
                  <div className="mt-4 flex items-center gap-3 rounded-2xl bg-[#f1f7f3] p-4 ring-1 ring-inset ring-[#0f3a26]/[0.06]">
                    <span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#006E42]/10 text-[#006E42]"><Utensils className="h-5 w-5" /></span>
                    <div className="min-w-0 flex-1">
                      <p className="text-[10.5px] font-semibold uppercase tracking-[0.12em] text-[#006E42]/70">{block.title}</p>
                      <p className="truncate text-[14px] font-bold text-[#0f3a26]">{info.name}</p>
                    </div>
                    <div className="shrink-0 text-right">
                      <p className="text-[9.5px] font-medium uppercase tracking-wide text-[#0f3a26]/40">Now</p>
                      <p className="text-[14px] font-bold tabular-nums text-[#0f3a26]">{curKcal} kcal</p>
                    </div>
                  </div>

                  {/* portion */}
                  <div className="mt-5 flex items-center justify-between">
                    <span className="text-[11px] font-semibold uppercase tracking-[0.12em] text-[#0f3a26]/55">Portion</span>
                    <span className="rounded-full bg-[#0f3a26]/[0.05] px-2 py-0.5 text-[10.5px] font-medium text-[#0f3a26]/50">{info.byLabel}</span>
                  </div>
                  <div className="mt-2 flex items-center gap-3">
                    <button onClick={() => bump(-info.step)} disabled={amount <= info.min} aria-label="Smaller portion" className={stepBtn}><Minus className="h-4 w-4" /></button>
                    <div className="flex flex-1 items-baseline justify-center gap-1.5 rounded-2xl bg-[#f6faf7] py-4 ring-1 ring-inset ring-[#0f3a26]/[0.08]">
                      <span className="text-[30px] font-bold leading-none tabular-nums text-[#0f3a26]">{fmtNum(amount)}</span>
                      <span className="text-[13px] font-semibold text-[#0f3a26]/50">{amount === 1 ? info.unitSingular : info.unitPlural}</span>
                    </div>
                    <button onClick={() => bump(info.step)} aria-label="Bigger portion" className={stepBtn}><Plus className="h-4 w-4" /></button>
                  </div>
                  <div className="mt-2.5 flex flex-wrap gap-1.5">
                    {info.chips.map((q) => (
                      <button key={q} onClick={() => setAmount(q)} className={`rounded-lg px-2.5 py-1 text-[11px] font-semibold transition ${amount === q ? "bg-[#006E42] text-white" : "bg-[#f1f7f3] text-[#0f3a26]/60 ring-1 ring-inset ring-[#0f3a26]/[0.08] hover:text-[#006E42]"}`}>{fmtNum(q)}{info.mode === "gram" ? " g" : ""}</button>
                    ))}
                  </div>

                  {/* result */}
                  <div className="mt-5 flex items-center justify-between rounded-2xl bg-[#006E42]/[0.07] px-4 py-3.5 ring-1 ring-inset ring-[#006E42]/15">
                    <div>
                      <p className="text-[9.5px] font-semibold uppercase tracking-[0.12em] text-[#006E42]/60">New total</p>
                      <span className="inline-flex items-center gap-1.5 text-[22px] font-bold tabular-nums text-[#006E42]"><Flame className="h-4 w-4 text-[#c79a3d]" />{newKcal} kcal</span>
                    </div>
                    {delta !== 0 && <span className={`rounded-full px-2.5 py-1 text-[11.5px] font-bold tabular-nums ${delta > 0 ? "bg-[#c79a3d]/15 text-[#9c7426]" : "bg-[#006E42]/12 text-[#006E42]"}`}>{delta > 0 ? "+" : ""}{delta} kcal</span>}
                  </div>

                  <button onClick={savePortion} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#006E42] px-4 py-2.5 text-[13px] font-semibold text-white transition hover:bg-[#005634]"><Check className="h-4 w-4" />Save portion</button>
                </div>
              ) : (
                <div className="flex h-full flex-col gap-3 bg-[#fbfdfb] p-4 sm:flex-row sm:gap-5 sm:p-5">
                  {/* filter rail */}
                  <div className="shrink-0 sm:w-44">
                    <p className="mb-2 hidden px-1 text-[10px] font-semibold uppercase tracking-[0.14em] text-[#0f3a26]/40 sm:block">Filter by</p>
                    <div className="no-scrollbar flex gap-1.5 overflow-x-auto pb-1 sm:flex-col sm:overflow-y-auto sm:pb-0">
                      <button onClick={() => setFilter("all")} className={chipCls(filter === "all")}>All meals</button>
                      {dietChips.map((d) => <button key={d.key} onClick={() => setFilter(d.key)} className={chipCls(filter === d.key)}>{d.label}</button>)}
                      {cuisineChips.length > 0 && <div className="mx-1 hidden h-px shrink-0 bg-[#0f3a26]/8 sm:my-1.5 sm:block" />}
                      {cuisineChips.map((c) => <button key={c} onClick={() => setFilter(`cuisine:${c}`)} className={chipCls(filter === `cuisine:${c}`)}>{c}</button>)}
                    </div>
                  </div>

                  {/* meal list */}
                  <div className="no-scrollbar min-h-0 flex-1 overflow-y-auto">
                    {!meals ? (
                      <div className="grid gap-2.5">{Array.from({ length: 4 }).map((_, i) => <div key={i} className="h-[92px] animate-pulse rounded-2xl bg-[#f1f7f3]" />)}</div>
                    ) : shown.length === 0 ? (
                      <div className="grid h-full min-h-40 place-items-center text-center text-[13px] text-[#0f3a26]/50">No meals in this category yet.</div>
                    ) : (
                      <>
                        <p className="mb-2.5 px-0.5 text-[11px] text-[#0f3a26]/45"><span className="font-bold text-[#0f3a26]/70">{shown.length}</span> meal{shown.length === 1 ? "" : "s"} to choose from</p>
                        <div className="grid gap-2.5">
                          {shown.map((m) => {
                            const dm = DIET_META[m.diet];
                            const current = block.detail === m.name;
                            return (
                              <div key={m.id} className={`group flex items-center gap-3 rounded-2xl p-2.5 ring-1 transition ${current ? "bg-[#006E42]/[0.06] ring-[#006E42]/30" : "bg-white ring-[#0f3a26]/8 hover:ring-[#006E42]/30 hover:shadow-[0_12px_30px_-20px_rgba(15,58,38,0.45)]"}`}>
                                <div className="relative h-[72px] w-[72px] shrink-0 overflow-hidden rounded-xl bg-[#f1f7f3]">
                                  <span className="absolute inset-0 bg-cover bg-center transition-transform duration-500 group-hover:scale-[1.06]" style={{ backgroundImage: `url(${m.image})` }} aria-hidden />
                                  {youtubeId(m.youtubeUrl) && <span className="absolute bottom-1 right-1 grid h-5 w-5 place-items-center rounded-full bg-black/55 text-white backdrop-blur-sm"><Play className="h-2.5 w-2.5 translate-x-[0.5px] fill-current" /></span>}
                                </div>
                                <div className="min-w-0 flex-1">
                                  <div className="flex items-center gap-1.5">
                                    <p className="truncate text-[14px] font-bold text-[#0f3a26]">{m.name}</p>
                                    <span className={`shrink-0 rounded-full px-1.5 py-0.5 text-[9px] font-semibold ${dm.cls}`}>{dm.short}</span>
                                  </div>
                                  {m.description && <p className="mt-0.5 line-clamp-1 text-[11px] leading-snug text-[#0f3a26]/55">{m.description}</p>}
                                  <div className="mt-1.5 flex items-center gap-2.5 text-[11px] font-semibold text-[#0f3a26]/60">
                                    <span className="inline-flex items-center gap-1"><Flame className="h-3 w-3 text-[#c79a3d]" />{m.kcal}</span>
                                    <span className="inline-flex items-center gap-1"><Dumbbell className="h-3 w-3 text-[#006E42]" />{m.protein}g</span>
                                    <span className="inline-flex items-center gap-1"><Timer className="h-3 w-3 text-[#0f3a26]/40" />{m.timeMins}m</span>
                                    <span className="ml-auto shrink-0 rounded bg-[#0f3a26]/[0.05] px-1.5 py-0.5 text-[9.5px] font-medium text-[#0f3a26]/50">{m.cuisine}</span>
                                  </div>
                                </div>
                                <button onClick={() => chooseMeal(m)} disabled={current} className={`shrink-0 rounded-full px-3.5 py-2 text-[12px] font-semibold transition ${current ? "bg-[#006E42] text-white" : "bg-[#006E42]/10 text-[#006E42] hover:bg-[#006E42] hover:text-white"}`}>{current ? "Selected" : "Select"}</button>
                              </div>
                            );
                          })}
                        </div>
                      </>
                    )}
                  </div>
                </div>
              )}
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
