export const healthTaglines: string[] = [
  "Small steps. Big shifts. Lasting health.",
  "Your body keeps score — make it a winning one.",
  "Nutrients before nootropics. Foundations first.",
  "Energy is a system, not a supplement.",
  "Track what matters. Skip what doesn't.",
  "Tiny daily wins compound into vitality.",
  "Health is a long game played one habit at a time.",
  "Movement is medicine — even ten minutes counts.",
  "Hydration is the cheapest performance enhancer.",
  "What you don't measure, you can't improve.",
  "Stress less. Stretch more. Sleep deeper.",
  "Real food first. Supplements where it counts.",
  "Better sleep tonight, sharper mind tomorrow.",
  "Strong body. Calm mind. Steady energy.",
  "Wellness isn't a destination — it's a rhythm.",
  "Less hustle. More restoration.",
  "The best workout is the one you'll do tomorrow too.",
  "Listen to your body before it has to shout.",
  "Consistency beats intensity. Every time.",
  "Slow mornings, focused days, restful nights.",
  "Your future self is built today.",
  "Whole foods. Whole sleep. Whole self.",
  "Prevention is the most underrated form of care.",
  "Breathe deeper. Most things look different at 4 counts.",
  "Protein at every meal. Energy through every hour.",
  "Sunlight before screens, every morning if you can.",
  "Walk after eating. The simplest blood-sugar hack.",
  "Magnesium quietly runs 300 reactions in your body.",
  "Your gut is a second brain. Feed it like one.",
  "Cold showers. Warm conversations. Both matter.",
  "Lift heavy things. Carry them. Put them down.",
  "Fiber feeds the bacteria that feed your mood.",
  "Strength training is anti-aging in disguise.",
  "Vitamin D is sunshine in a capsule.",
  "Iron deficiency hides as fatigue for years.",
  "B12 quietly powers focus, mood, and nerves.",
  "Three deep breaths can reset your nervous system.",
  "Posture is the cheapest form of confidence.",
  "Eat the rainbow. Each color carries different antioxidants.",
  "Sleep is when your body rebuilds. Don't skip it.",
  "Fasted walks burn fat. Fed walks build joy.",
  "Stretching ten minutes a day buys you decades.",
  "Your morning sets your day. Protect the first hour.",
  "A short walk is better than a perfect workout you skipped.",
  "Omega-3s are non-negotiable for brain longevity.",
  "Hydrate first. Caffeinate second.",
  "Chew slowly. Digest deeply. Sleep better.",
  "Mood follows movement, not the other way around.",
  "Get bored sometimes. The dopamine reset is real.",
  "Quit perfection. Choose presence.",
  "Cook one more meal at home this week. Just one.",
  "Track your sleep before you track anything else.",
  "Most cravings are thirst in disguise.",
  "Recovery isn't a reward. It's the workout.",
  "Vitamin C boosts iron absorption. Pair them.",
  "Your microbiome is more you than your DNA.",
  "Sleep regular hours. Your hormones thrive on rhythm.",
  "Add greens to one meal a day. Watch energy return.",
  "Stand more. Sit less. The chair is not your friend.",
  "Heavy weights, light meals, deep sleep.",
  "Less sugar. Sharper mind. Quieter cravings.",
  "Breathwork is the gym for your nervous system.",
  "A 20-minute nap beats a third cup of coffee.",
  "Your skin reflects what your gut absorbs.",
  "Zone 2 cardio is the longevity sweet spot.",
  "Get your bloodwork done annually. No exceptions.",
  "Sleep in a dark, cool, quiet room. Always.",
  "Friendship is a vitamin nobody talks about.",
  "Reduce alcohol. Notice how much sharper everything is.",
  "Protein, fiber, fat. Every meal, every time.",
  "Find a body you'd happily inhabit for 80 more years.",
  "Curiosity is the antidote to burnout.",
  "Skip the elevator. Take the stairs. Always.",
  "Two minutes of sun on your skin beats a screen detox.",
  "Don't outsource your sleep to a substance.",
  "Building muscle in your 30s pays dividends in your 70s.",
  "Mind your minerals. They run your electricity.",
  "Drink water like it's your job. It is.",
  "Eat less than you think. Move more than you want.",
  "Your knees thank you for the walks you take today.",
  "Curiosity, sunlight, sleep. The big three.",
  "Don't chase metrics. Chase how you feel.",
  "Cravings fade in 20 minutes. So do bad moods.",
  "Better choices start with better questions.",
  "Pick a sport, not a workout. Keep it fun.",
  "Inflammation hides in seed oils and stress.",
  "Slow weights build fast results.",
  "Your habits today are your medications tomorrow.",
];
